language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8"
install:
- pip install pytest
- pip install coveralls
script:
- coverage run --source customblocks -m pytest -v
after_success:
- coveralls


