site_name: Markdown Custom Blocks
site_url: https://vokimon.github.io/markdown-customblocks
site_author: vokimon
site_description: Parametrizable and nestable custom components for Markdown
repo_url: https://github.com/vokimon/markdown-customblocks/
#watch:
#  - customblocks
nav:
  - First steps: README.md
  - Built-in generators:
    - Container: generators-container.md
    - Admonition: generators-admonition.md
    - Figure: generators-figure.md
    - Map: generators-map.md
    - Linkcard: generators-linkcard.md
    - Wikipedia: generators-wikipedia.md
    - Youtube: generators-youtube.md
    - Peertube: generators-peertube.md
    - Vimeo: generators-vimeo.md
    - Mastodon: generators-mastodon.md
    - Twitter: generators-twitter.md
    - Instagram: generators-instagram.md
    - Facebook: generators-facebook.md
    - Verkami: generators-verkami.md
    - Goteo: generators-goteo.md
  - Creating new block types: defining-generators.md
  #- Tutorial: tutorial.md
  - Project:
    - Motivation and design choices: motivation.md
    - Inspiration: inspiration.md
    - Release History: CHANGES.md
    - Road Map: TODO.md
markdown_extensions:
  - customblocks
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - css/figure.css
  - css/linkcard.css
  - css/videowrapper.css
  - #css/admonition.css
  - extra.css
theme:
  logo:  img/logo-customblocks-white.svg
  name: material
  language: en
  extra:
    include_toc: true
  highlightjs: true
  hljs_languages:
    - yaml
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  version:
    provider: mike
  features:
    - navigation.instant # load content instead of refreshing the page
    - navigation.sections
  plugins:
    - mike:
        # these fields are all optional; the defaults are as below...
        version_selector: true   # set to false to leave out the version selector
        css_dir: css             # the directory to put the version selector's CSS
        javascript_dir: js       # the directory to put the version selector's JS
        canonical_version: null  # the version for <link rel="canonical">; `null`
         # uses the version specified via `mike deploy`
    - offline 


